### ISSUE TITLE
Add example command for installing dependencies to README.md

### ISSUE THREAD

**Issue by stevesimmons** [rocketraman/sane-scan-pdf#14]
Can you please add a line in the Requirements section on how to install the dependencies?

The package names for Ubuntu are:
> `sudo apt install netpbm ghostscript poppler-utils imagemagick unpaper util-linux tesseract-ocr parallel`

If you prefer, I can add this in a pull request.

**Comment by rocketraman** [comment]
I normally run the script on Fedora, not Ubuntu, so this isn't something I can really maintain easily. What I think we can do though, at least for now, is create a wiki page for this.

See https://github.com/rocketraman/sane-scan-pdf/wiki/Dependencies-Installation.

I'll add a link to this in the README also.
