### ISSUE TITLE
units: command not found

### ISSUE THREAD

**Issue by timcknowles** [rocketraman/sane-scan-pdf#15]
Thanks for this script. I know people have had success on Debian / Rasperry Pi. When I run the script I encounter this.

scan: line 201: units: command not found
scan: line 207: units: command not found
Scanning...
scanadf: open of device fujitsu failed: Invalid argument

Any advice greatly appreciated

**Comment by rocketraman** [comment]
@timcknowles You need to find what package provides the `units` command. On Fedora it is "units". Check out https://www.cyberciti.biz/faq/equivalent-of-rpm-qf-command/.

Please post here to let me know which package provides it, and we'll update the wiki page about dependencies: https://github.com/rocketraman/sane-scan-pdf/wiki/Dependencies-Installation.

**Comment by rocketraman** [comment]
I added units to the dependency list here: ed98da9c438ee4781f869df0e981bc946d4247ac.

**Comment by timcknowles** [comment]
Thanks for the speedy reply. I can confirm its the "units" package in Raspberry Pi OS/ Debian also. Thanks Tim

**Comment by rocketraman** [comment]
Thanks, wiki updated!
