### ISSUE TITLE
My scanadf does not recognize --page-height 

### ISSUE THREAD

**Issue by p** [rocketraman/sane-scan-pdf#23]
The default invocations of `scan` aren't working for me, and I would appreciate any assistance with figuring out what I am missing.

The minimum invocation with specifying the device only fails with `scanadf` not recognizing the `--page-height` option:

```
scan% bash -x  ./scan -x 'brother4:bus7;dev1'                          
...
+ eval scanadf -d ''\''brother4:bus7;dev1'\''' --page-height 279.4 -y 279.4 --page-width 215.9 -x 215.9 -S /home/bootstrap/sane-scan-pdf/scan_perpage --script-wait --resolution 300 Lineart 0 0 -o /tmp/scan.EvTCrlOk58/scan-%04d
++ scanadf -d 'brother4:bus7;dev1' --page-height 279.4 -y 279.4 --page-width 215.9 -x 215.9 -S /home/bootstrap/sane-scan-pdf/scan_perpage --script-wait --resolution 300 Lineart 0 0 -o /tmp/scan.EvTCrlOk58/scan-%04d
scanadf: unrecognized option '--page-height'
```

After I add `--no-default-size`, this works, but if I add `--crop`, `scan` puts in the `--page-height` option back which once again fails:

```
scan% bash -x  ./scan -x 'brother4:bus7;dev1'  --no-default-size -m '' --unpaper --crop
+ eval scanadf -d ''\''brother4:bus7;dev1'\''' --page-height 9999 -y 9999 --page-width 9999 -x 9999 -S /home/bootstrap/sane-scan-pdf/scan_perpage --script-wait --resolution 300 0 --swcrop=yes --ald=yes -o /tmp/scan.u3O3Dx0Zi8/scan-%04d
++ scanadf -d 'brother4:bus7;dev1' --page-height 9999 -y 9999 --page-width 9999 -x 9999 -S /home/bootstrap/sane-scan-pdf/scan_perpage --script-wait --resolution 300 0 --swcrop=yes --ald=yes -o /tmp/scan.u3O3Dx0Zi8/scan-%04d
scanadf: unrecognized option '--page-height'
```

The [scanadf manpage](http://sane-project.org/man/scanadf.1.html) does not appear to mention `--page-height`, is that option supposed to be recognized by `scanadf` or some other program?

My software versions:

```
scan% dpkg -l|grep sane                                                                
ii  libsane:amd64                        1.0.31-4                           amd64        API library for scanners [transitional package]
ii  libsane-common                       1.0.31-4                           all          API library for scanners -- documentation and support files
ii  libsane1:amd64                       1.0.31-4                           amd64        API library for scanners
ii  sane                                 1.0.14-16                          amd64        scanner graphical frontends
ii  sane-utils                           1.0.31-4                           amd64        API library for scanners -- utilities
```

I saw that the current sane version is 1.0.32, I retrieved git source for sane-frontends and I'm still not seeing the `--page-height` option in `scanadf` there.

Appreciate any insights as to how to get the `--page-height` working. Alternatively I can submit a PR that would make `scan` not pass it (via a new option perhaps?) if this is preferable.

**Comment by rocketraman** [comment]
Yeah, `--page-height` is a device specific option in `scanadf`. My S1500 has it, as do probably most other ADF scanners, but other devices may not support it.

The intent of the `--no-default-size` option was to handle devices that do not support the page size arguments.

However, I see that this section of the script ignores `--no-default-size` when `--crop` is specified: https://github.com/rocketraman/sane-scan-pdf/blob/master/scan#L217-L224. This was added before `--no-default-size` to fix https://github.com/rocketraman/sane-scan-pdf/issues/8.

Does your driver support the `--sw-crop` and `--ald` options? You can do `scanadf --help -d <device>` to see the device-specific options.

Some possible changes here, which I think will partially depend on your answer to the above:

* Modify L217-L224 to not set the page height and width if `--no-default-size` is set. It will likely break hardware-based cropping when in duplex mode though.
* Therefore, could potentially make it an error to do `--crop` and `--duplex` and `--no-default-size` together.

**Comment by p** [comment]
I have this:

```
scan% scanadf -d  'brother4:bus7;dev1'  --help
Usage: scanadf [OPTION]...

Start image acquisition on a scanner device and write image data to
output files.

   [ -d | --device-name <device> ]   use a given scanner device.
   [ -h | --help ]                   display this help message and exit.
   [ -L | --list-devices ]           show available scanner devices.
   [ -v | --verbose ]                give even more status messages.
   [ -V | --version ]                print version information.
   [ -N | --no-overwrite ]           don't overwrite existing files.

   [ -o | --output-file <name> ]     name of file to write image data
                                     (%d replacement in output file name).
   [ -S | --scan-script <name> ]     name of script to run after every scan.
   [ --script-wait ]                 wait for scripts to finish before exit
   [ -s | --start-count <num> ]      page count of first scanned image.
   [ -e | --end-count <num> ]        last page number to scan.
   [ -r | --raw ]                    write raw image data to file.
scanadf: rounded value of br-x from 211.9 to 211.881
scanadf: rounded value of br-y from 355.6 to 355.567

Options specific to device `brother4:bus7;dev1':
  Mode:
    --mode Black & White|Gray[Error Diffusion]|True Gray|24bit Color|24bit Color[Fast] [24bit Color[Fast]]
        Select the scan mode
    --resolution 100|150|200|300|400|600|1200|2400|4800|9600dpi [200]
        Sets the resolution of the scanned image.
    --source FlatBed|Automatic Document Feeder(left aligned)|Automatic Document Feeder(centrally aligned) [Automatic Document Feeder(left aligned)]
        Selects the scan source (such as a document-feeder).
    --brightness -50..50% (in steps of 1) [inactive]
        Controls the brightness of the acquired image.
    --contrast -50..50% (in steps of 1) [inactive]
        Controls the contrast of the acquired image.
  Geometry:
    -l 0..211.9mm (in steps of 0.0999908) [0]
        Top-left x position of scan area.
    -t 0..355.6mm (in steps of 0.0999908) [0]
        Top-left y position of scan area.
    -x 0..211.9mm (in steps of 0.0999908) [211.881]
        Width of scan-area.
    -y 0..355.6mm (in steps of 0.0999908) [355.567]
        Height of scan-area.

Type ``scanadf --help -d DEVICE'' to get list of all options for DEVICE.

List of available devices:
    brother4:bus7;dev1
munmap_chunk(): invalid pointer
zsh: abort      scanadf -d 'brother4:bus7;dev1' --help
```

Would the `-y` option be semantically providing the same functionality as --page-height?

**Comment by rocketraman** [comment]
>     --mode Black & White|Gray[Error Diffusion]|True Gray|24bit Color|24bit Color[Fast] [24bit Color[Fast]]
>         Select the scan mode

As an aside, I see now why "Color" wasn't working for you... your other option would have been to just specify the driver mode explicitly: `--mode="24bit Color[Fast]"`, but I do still like the `--mode-hw-default` switch, which is easier to type.

> Would the `-y` option be semantically providing the same functionality as --page-height?

My scanner supports both, and generally both are supposed to be set when supported. The `--page-height` option supports centering of the scan coordinates when using an ADF, and for detecting double feed errors. See `man sane-fujitsu` for example.

```
    --page-height 0..876.695mm (in steps of 0.0211639) [279.364]
        Specifies the height of the media.
   ...
    -y 0..279.364mm (in steps of 0.0211639) [279.364]
        Height of scan-area.
```

The guy that originally reported the issue that resulted in the addition of `--no-default-size` was using the `epjitsu` driver, which does not support the `-y` option. :-( See https://github.com/rocketraman/sane-scan-pdf/issues/16 and `man sane-epjitsu`.

Since your scanner supports `-y` but not `--page-height`, maybe we need another option `--no-default-pagesize` which would continue to use `-y` and `-x` but not `--page-height` and `--page-width`.

**Comment by p** [comment]
They weren't in the above help output, and as far as I can tell my `scanadf` doesn't support `--swcrop` and `--ald`:

```
scan% scanadf -d 'brother4:bus7;dev1'  -y 9999  -x 9999 -S /home/bootstrap/sane-scan-pdf/scan_perpage --script-wait --resolution 300 --mode 'Black & White' 0 --swcrop=yes --ald=yes -o /tmp/scan.ckyyQ68rXp/scan-%04d
scanadf: unrecognized option '--swcrop=yes'
```
```
scan% scanadf -d 'brother4:bus7;dev1'  -y 9999  -x 9999 -S /home/bootstrap/sane-scan-pdf/scan_perpage --script-wait --resolution 300 --mode 'Black & White' 0  --ald=yes -o /tmp/scan.ckyyQ68rXp/scan-%04d 
scanadf: unrecognized option '--ald=yes'
```

I am looking into the page height situation.

**Comment by p** [comment]
After applying https://github.com/p/sane-scan-pdf/commit/67e4f86e6b4faa89327148388468965522914382 to remove --page-width/--page-height arguments and #27 to fix argument processing, I get:

```
scan% bash -x  ./scan -x 'brother4:bus7;dev1'  --no-default-size   --mode-hw-default --crop -o 3.pdf
...
+ eval scanadf -d ''\''brother4:bus7;dev1'\''' -y 9999 -x 9999 -S /home/bootstrap/sane-scan-pdf/scan_perpage --script-wait --resolution 300 0 --swcrop=yes --ald=yes -o /tmp/scan.YUGCG36agf/scan-%04d
++ scanadf -d 'brother4:bus7;dev1' -y 9999 -x 9999 -S /home/bootstrap/sane-scan-pdf/scan_perpage --script-wait --resolution 300 0 --swcrop=yes --ald=yes -o /tmp/scan.YUGCG36agf/scan-%04d
scanadf: unrecognized option '--swcrop=yes'
```

I take it this means `--crop` doesn't work for me? Readme says "driver must support [--crop]", does this mean unpaper doesn't offer similar feature?

**Comment by rocketraman** [comment]
> I take it this means --crop doesn't work for me? Readme says "driver must support [--crop]", does this mean unpaper doesn't offer similar feature?

Yeah, currently `--crop` relies on driver support. Its possible unpaper has something similar but I haven't looked into it. I'm not opposed to a software-based crop being implemented.

**Comment by p** [comment]
Okay,  I'm going to give up on cropping in my environment on account of it apparently not working.

You mentioned earlier that

> Therefore, could potentially make it an error to do --crop and --duplex and --no-default-size together.

I can submit a PR to do that or whatever you think is missing since I'm editing the code anyway, but  as I haven't been able to get cropping working I won't be able to test it.

Or if it makes more sense, this ticket can be closed.

**Comment by rocketraman** [comment]
If your scanner doesn't support the crop options, then I think there is no point in making any other changes for now. Therefore, I'll close, but feel free to re-open if you have any other ideas.
