### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by OhHeyAlan** [rocketraman/sane-scan-pdf#43]
I have a ScanSnap S1500 and I can't figure out how to rotate all the images 180 degrees, since they all come out upside down...  Can anyone point me in the right direction?

**Comment by mgray88** [comment]
Put the paper in the other way?

**Comment by rocketraman** [comment]
The right way to place the paper on the S1500 is with the front side down, and the top of the paper feeding in first. If you're placing it that way and things are still upside down, then please re-open/comment. Thanks!

**Comment by OhHeyAlan** [comment]
@rocketraman This will take some getting use to... For 8 years I used it on Windows, paper facing backward, top still on top and the orientation on the computer was always correct. Sorry for opening a issue over a user error.

**Comment by rocketraman** [comment]
@OhHeyAlan No worries. I suspect the windows driver for the scanner does some magic to rotate the pages for you when you put them in the wrong way.

**Comment by rocketraman** [comment]
I'm really surprised you never had a false negative in 8 years though...
