### ISSUE TITLE
Settings SOURCE=ADF doesn't work on brother MFC-L2700DW

### ISSUE THREAD

**Issue by andhawk** [rocketraman/sane-scan-pdf#44]
Also tried 
  SOURCE="ADF"

It's not a big problem as I can use
  DRIVER_OPTION="--source ADF"

But just in case it points to a problem in the script you can help me understand the problem please

`Options specific to device `airscan:w1:Brother':
  Standard:
    --resolution 100|200|300dpi [300]
        Sets the resolution of the scanned image.
    --mode Color|Gray [Color]
        Selects the scan mode (e.g., lineart, monochrome, or color).
    --source Flatbed|ADF [Flatbed]
        Selects the scan source (such as a document-feeder).
  Geometry:
    -l 0..215.9mm [0]
        Top-left x position of scan area.
    -t 0..297.18mm [0]
        Top-left y position of scan area.
    -x 0..215.9mm [215.9]
        Width of scan-area.
    -y 0..297.18mm [297.18]
        Height of scan-area.
  Enhancement:
    --brightness -100..100% (in steps of 1) [0]
        Controls the brightness of the acquired image.
    --contrast -100..100% (in steps of 1) [0]
        Controls the contrast of the acquired image.
    --shadow 0..100% (in steps of 1) [0]
        Selects what radiance level should be considered "black".
    --highlight 0..100% (in steps of 1) [100]
        Selects what radiance level should be considered "white".
    --analog-gamma 0.0999908..4 [1]
        Analog gamma-correction
    --negative[=(yes|no)] [no]
        Swap black and white
`

**Comment by rocketraman** [comment]
Can you try doing a scan with `--verbose` to see if that gives any hints? Judging by the driver options you posted, it seems like it should be working.

**Comment by rocketraman** [comment]
No debug information available, closing.
