### ISSUE TITLE
Page not aligning correctly

### ISSUE THREAD

**Issue by bigshit11elf** [rocketraman/sane-scan-pdf#52]
RaspberryPi 3+
Ubuntu Server 23.04
Epson DS-310

Scanning with just a scanadf command issued per hand, the scanner is able to scan the whole page. During post processing something must go wrong, as the top of the page is cut off from the final converted PDF. It looks like the original image is moved out of the top of the resulting page. --> In this case the resulting page is A4-sized. Part of the scanned top is missing while whitespace below the scanned page is added.

Please tell me what I need to provide in order for you to fix the problem. Thanks in advance!

#EDIT: Not happening when using OCR option. --> In this case the resulting page is a custom size that is way longer than A4. The top is fully there but also whitespace is added below.

**Comment by bigshit11elf** [comment]
Adding info: Scanning an A4 page I get the following output.

`pnmtops: Image will be 610.56 points wide by 1043.28 points high, left edge 0.72 points from left edge of page, bottom edge -125.64 points from bottom of page; NOT turned to landscape orientation`

**Comment by rocketraman** [comment]
If none of that works, then provide the output of:

```
scanadf --help -d <DEVICE>
```

and the output of a verbose scan (`-v` option).

**Comment by rocketraman** [comment]
> The error only occurs when I scan without OCR. So the ocr processing seems to do something correctly that the other way does not…

That's quite possible -- when doing OCR, the OCR software (Tesseract) takes over responsibility for converting the output to PDF. When not doing OCR, it is done via `pnmtops` and `ps2pdf`. The verbose output should tell us what page options are being passed to those tools.

The `--no-default-size` option is not super well tested as I don't use it myself, so its quite likely there is a bug. Thanks for raising the issue!

**Comment by rocketraman** [comment]
I do still want the output of `--help -d <DEVICE>` as well. And also helpful would be the command line you are using and the content of any config files.

**Comment by bigshit11elf** [comment]
Output of `sudo scandadf --help -d "epsonscan2"`

```
Start image acquisition on a scanner device and write image data to
output files.

   [ -d | --device-name <device> ]   use a given scanner device.
   [ -h | --help ]                   display this help message and exit.
   [ -L | --list-devices ]           show available scanner devices.
   [ -v | --verbose ]                give even more status messages.
   [ -V | --version ]                print version information.
   [ -N | --no-overwrite ]           don't overwrite existing files.

   [ -o | --output-file <name> ]     name of file to write image data
                                     (%d replacement in output file name).
   [ -S | --scan-script <name> ]     name of script to run after every scan.
   [ --script-wait ]                 wait for scripts to finish before exit
   [ -s | --start-count <num> ]      page count of first scanned image.
   [ -e | --end-count <num> ]        last page number to scan.
   [ -r | --raw ]                    write raw image data to file.
/etc/es2button/default: line 2:  1412 Segmentation fault      (core dumped) scanadf --help -d epsonscan2
```



No matter what I try, I cannot get the scanner to not produce a segmentation fault, here. But I am pretty sure this is because of a proprietary method I use to get its button status...

If you look at the scanned files, the `test-scan-pnmtops-0001` is totally fine before conversion. After conversion (`test-scan-pnmtops.pdf`) it does not get placed right on the output file. In comparison `test-scan-ocr.pdf` is totally fine - tesseract places the scan in the right place on the output page.

You can see the scripts I use to start the scans here:

```
#script to trigger the pnmtops scan
#!/bin/sh
now=`date +"%Y-%m-%d-%H%M"`
/home/USERNAME/sane-scan-pdf/scan -d -r 200 -v -m Color --device "" -xo "-t 0 -l 0 --adf-crp no --adf-skew no" --no-default-size -o /mnt/scans/scan-$now.pdf
```

```
#script to trigger the ocr tesseract scan
#!/bin/sh
now=`date +"%Y-%m-%d-%H%M"`
/home/ribecker/sane-scan-pdf/scan -d -r 200 -v -m Color --device "" -xo "-y 297.0" --no-default-size --ocr --language deu  -o /mnt/scans/scan-$now.pdf
```

[test-scan-pnmtops.pdf](https://github.com/rocketraman/sane-scan-pdf/files/12164277/test-scan-pnmtops.pdf)
[test-scan-ocr.pdf](https://github.com/rocketraman/sane-scan-pdf/files/12164278/test-scan-ocr.pdf)
[pnm.zip](https://github.com/rocketraman/sane-scan-pdf/files/12164287/pnm.zip)

**Comment by bigshit11elf** [comment]
Forgot the verbose output. Here it is for both versions of scanning:
[verbose output scan-ocr.txt](https://github.com/rocketraman/sane-scan-pdf/files/12164347/verbose.output.scan-ocr.txt)
[verbose output scan-pnmtops.txt](https://github.com/rocketraman/sane-scan-pdf/files/12164348/verbose.output.scan-pnmtops.txt)
[scan-ocr.pdf](https://github.com/rocketraman/sane-scan-pdf/files/12164349/scan-ocr.pdf)
[scan-pnmtops.pdf](https://github.com/rocketraman/sane-scan-pdf/files/12164350/scan-pnmtops.pdf)

**Comment by rocketraman** [comment]
@bigshit11elf Looking at test-scan-pnmtops-0001, I see that it has dimensions:

```
test-scan-pnmtops-0001.pnm: Netpbm image data, size = 1696 x 2898, rawbits, pixmap
```

Scanning at 200 dpi, this means the dimensions are 8.48" x 14.49", which is quite a bit larger  (especially in length) than a4. The conversion which then subsequently messes things up is `ps2pdf`, but I'm not completely surprised about that given that it has no idea how to convert this larger size into the smaller a4.

There are a bunch of switches we could play with at each processing step but I'm thinking before we start digging into that, lets figure out why the input is sized the way it is.

I see the comand line uses the option `--adf-crp no`. Judging by the name of that, I'm guessing that tells the driver to return the image with the entire ADF scan area, rather than just the paper area. Can you try removing that option and see what happens?

**Comment by bigshit11elf** [comment]
1st try: "--adf-crp yes"

returns the full size of the ADF, again - no cropping by the driver happening

Will try to remove the option in a second.


(Thanks for your follow-up!)
[scan-2023-07-31-1801.pdf](https://github.com/rocketraman/sane-scan-pdf/files/12216957/scan-2023-07-31-1801.pdf)
[scan-2023-07-31-1801.zip](https://github.com/rocketraman/sane-scan-pdf/files/12216970/scan-2023-07-31-1801.zip)

**Comment by bigshit11elf** [comment]
2nd try: "--adf-crp no" and "--adf-skew no" removed

returns the full size of the ADF, again - no cropping by the driver happening
[scan-2023-07-31-1806.pdf](https://github.com/rocketraman/sane-scan-pdf/files/12217005/scan-2023-07-31-1806.pdf)
[scan-2023-07-31-1806.zip](https://github.com/rocketraman/sane-scan-pdf/files/12217006/scan-2023-07-31-1806.zip)

**Comment by bigshit11elf** [comment]
And more info:

Was able to get a device list from `scanadf -L`

`device 'epsonds:libusb:001:015' is a Epson DS-310 ESC/I-2
device 'epsonscan2:DS-310:001:015:esci2:usb:ES013E:345' is a EPSON DS-310:001:015 flatbed scanner`

Only one scanner is actually attached and used by SANE, the `epsonds`. The `epsonscan2` seems to be used by a plugin I installed to get the scanner button press event. But actual scanning is done by SANE using the `epsonds` driver, the other one does not communicate with SANE at all (commands just fail, not even producing an error message).

And when I tried getting the options for the `epsonds` via `scandf --help -d "epsonds"` it responded with the following info:

`Usage: scanadf [OPTION]...

Start image acquisition on a scanner device and write image data to
output files.

   [ -d | --device-name <device> ]   use a given scanner device.
   [ -h | --help ]                   display this help message and exit.
   [ -L | --list-devices ]           show available scanner devices.
   [ -v | --verbose ]                give even more status messages.
   [ -V | --version ]                print version information.
   [ -N | --no-overwrite ]           don't overwrite existing files.

   [ -o | --output-file <name> ]     name of file to write image data
                                     (%d replacement in output file name).
   [ -S | --scan-script <name> ]     name of script to run after every scan.
   [ --script-wait ]                 wait for scripts to finish before exit
   [ -s | --start-count <num> ]      page count of first scanned image.
   [ -e | --end-count <num> ]        last page number to scan.
   [ -r | --raw ]                    write raw image data to file.

Options specific to device 'epsonds':
  Standard:
    --source ADF Front|ADF Duplex [ADF Front]
        Selects the scan source (such as a document-feeder).
    --mode Lineart|Gray|Color [Color]
        Selects the scan mode (e.g., lineart, monochrome, or color).
    --depth 1|8bit [8]
        Number of bits per sample, typical values are 1 for "line-art" and 8
        for multibit scans.
    --resolution 200|300|400|600dpi [200]
        Sets the resolution of the scanned image.
  Geometry:
    -l 0..215.9mm [0]
        Top-left x position of scan area.
    -t 0..368.3mm [0]
        Top-left y position of scan area.
    -x 0..215.9mm [215.9]
        Width of scan-area.
    -y 0..368.3mm [368.3]
        Height of scan-area.
  Optional equipment:
    --eject
        Eject the sheet in the ADF
    --load
        Load a sheet in the ADF
    --adf-skew[=(yes|no)] [no]
        Enables ADF skew correction
    --adf-crp[=(yes|no)] [no]
        Enables ADF auto cropping

Type "scanadf --help -d DEVICE" to get list of all options for DEVICE.

List of available devices:
    epsonds:libusb:001:015 epsonscan2:DS-310:001:015:esci2:usb:ES013E:345`
    
    
Best regards - and still thanks for looking into the problem!

**Comment by rocketraman** [comment]
It looks like your scanner supports the `-x` and `-y` geometry settings but not the `--page-height` and `--page-width` settings which I believe my Fujitsu scanner uses for centering and length for sheet-fed scans.

Can you try applying this patch and then running the scan with `--size A4`? If this fixes the problem for you I can think about how to set up the options for this scenario.

```
diff --git a/scan b/scan
index 27962c8..c606b09 100755
--- a/scan
+++ b/scan
@@ -333,13 +333,13 @@ fi
 
 if [[ $CROP != 1 && "$PGHEIGHT" != "" ]]; then
   PGHEIGHTIN=$(units --compact -1 "$PGHEIGHT mm" 'in')
-  PGHEIGHT="--page-height $PGHEIGHT -y $PGHEIGHT"
+  PGHEIGHT="-y $PGHEIGHT"
   PS2PDF_OPTS="-dEPSCrop"
 fi
 
 if [[ $CROP != 1 && "$PGWIDTH" != "" ]]; then
   PGWIDTHIN=$(units --compact -1 "$PGWIDTH mm" 'in')
-  PGWIDTH="--page-width $PGWIDTH -x $PGWIDTH"
+  PGWIDTH="-x $PGWIDTH"
   PS2PDF_OPTS="-dEPSCrop"
 fi
 
@@ -347,8 +347,8 @@ if [[ $CROP == 1 ]]; then
   CROP="--swcrop=yes --ald=yes"
   # In duplex mode, the driver's buffer for the back side image will be larger than necessary, oh well
   # http://sane.10972.n7.nabble.com/Fujitsu-backend-and-iX500-scanning-page-longer-than-14-Inches-td19303.html
-  PGHEIGHT="--page-height 9999 -y 9999"
-  PGWIDTH="--page-width 9999 -x 9999"
+  PGHEIGHT="-y 9999"
+  PGWIDTH="-x 9999"
   PS2PDF_OPTS="-dEPSCrop"
 fi

```

**Comment by rocketraman** [comment]
@bigshit11elf Any updates based on my last message?

**Comment by rocketraman** [comment]
@bigshit11elf Any updates?

**Comment by rocketraman** [comment]
@bigshit11elf Did you have a chance to try that patch?

**Comment by rocketraman** [comment]
For anyone who encounters this in the future, see [this comment](https://github.com/rocketraman/sane-scan-pdf/issues/55#issuecomment-1749929209) for a solution.
