### ISSUE TITLE
How to select the ADF as a source for scanning

### ISSUE THREAD

**Issue by maciex** [rocketraman/sane-scan-pdf#54]
How to select the ADF as a source for scanning?

I have a Brother device (Brother DCP-L3550CDW series) and would like to scan from ADF. The script doesn't seem to allow me to select ADF as a source. As a workaround I modified the script and hardcoded `--source ADF` parameter with this patch:
```
diff --git a/scan b/scan
index 27962c8..4c13430 100755
--- a/scan
+++ b/scan
@@ -301,6 +301,8 @@ fi
 
 if [[ $DUPLEX == 1 ]]; then
   SOURCE="--source \"ADF Duplex\""
+else
+  SOURCE="--source ADF"
 fi
```

**Comment by rocketraman** [comment]
@maciex Try out the latest master, you can now specific `--source` and `--source-duplex` options. You can also save these in your default config.

**Comment by rocketraman** [comment]
Fixed by https://github.com/rocketraman/sane-scan-pdf/commit/dc2a67b1345851d51c88229278374c780c3fbf2c
