### ISSUE TITLE
--verbose flag breaks post-processing on Ubuntu/Debian

### ISSUE THREAD

**Issue by gbirke** [rocketraman/sane-scan-pdf#6]
Debian and Ubuntu use a very old version of netpbm (from 2002) which does not support the `-verbose` flag. When using the `-v`flag for the scan script, the `pbmtops` command fails.

As a workaround I've commented out the PNMVERBOSE variable in line 91 of `scan_perpage`. Of course it would be nicer to have a version check to ignore it, but I#m not up for that task.

**Comment by cbschuld** [comment]
@gbirke - I had the same experience; the work around fixed it as well.  I removed the three lines - everything works perfectly now.

**Comment by rocketraman** [comment]
@gbirke @cbschuld Can you guys test the code in PR #7 and see if that solves the problem for you?
